title: 'Leonardo Theme'
default_lang: en
author:
  name: 'Emel Rizvanovic'
  email: emel@upkeepmedia.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
